### ISSUE TITLE
Persistence to disk

### ISSUE THREAD

**Issue by treidio** [dritchie/adnn#24]
Hi,

how can I save a nn I've trained up to disk, and load into NodeJS again?

thanks in advance.

**Comment by dritchie** [comment]
If you have the nn params in a javascript object (i.e. the way params are passed around in the `opt` module methods), then you can pretty much just JSON.serialize that object. The only caveat is that you'll want to handle the Tensor objects a bit specially (so that they can be recognized as instances of the Tensor class when they're deserialized). Here's some code that I've used to do this in a project that uses adnn:

```js
'use strict';

var _ = require('lodash')
var Tensor = require('../tensor');

function tensorToObject(tensor) {
  return {
    dims: tensor.dims,
    data: tensor.toFlatArray()
  };
}

function tensorsToObjects(paramObj) {
  var prms = _.mapValues(paramObj, function(lst) {
    return lst.map(tensorToObject);
  });
  return prms;
}

function objectsToTensors(paramObj) {
  var prms = {};
  for (var name in paramObj) {
    prms[name] = paramObj[name].map(function(tensor) {
      return new Tensor(tensor.dims).fromFlatArray(tensor.data);
    });
  }
  return prms;
}

function serializeParams(paramObj) {
  return JSON.stringify(tensorsToObjects(paramObj));
}

function deserializeParams(str) {
  return objectsToTensors(JSON.parse(str));
}

module.exports = {
  tensorsToObjects: tensorsToObjects,
  objectsToTensors: objectsToTensors,
  serializeParams: serializeParams,
  deserializeParams: deserializeParams
};
```

**Comment by treidio** [comment]
thanks. 
I found this, which seems to help :) 
https://www.npmjs.com/package/serialization
